### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by duongbk61** [mortezagolzan/Face-Anti-Spoofing#1]
Tks for your work. Can you share your pretrained model? It will help me a lot.

**Comment by mortezagolzan** [comment]
> Tks for your work. Can you share your pretrained model? It will help me a lot.

Hi
Please send me your email.

**Comment by thonglv21** [comment]
My email is chonguoinoiay21@gmail.com. Could you please send to me your pre-trained model? Thank you a lot.

**Comment by chuongnvk54** [comment]
Hi @mortezagolzan  could you share me your pretrained model. My email is chuongnv.k54@gmail.com. Thanks you a lot

**Comment by nguyentu20398** [comment]
Hi @mortezagolzan could you share me your pretrained model. My email is [nguyentu20398@gmai.com](mailto:nguyentu20398@gmai.com). Thanks you a lot.

**Comment by duyquang392** [comment]
Hi @mortezagolzan could you share me your pretrained model. My email is [duyquang392@gmai.com](mailto:duyquang392@gmai.com). Thanks you a lot.

**Comment by faraz-fatahnaie** [comment]
Hi @mortezagolzan could you share me your pretrained model. My email is [faraz.fatahnaie@gmail.com]. Thanks you a lot.
