### ISSUE TITLE
Face-Anti-Spoofing dataset 

### ISSUE THREAD

**Issue by AZuhaira** [mortezagolzan/Face-Anti-Spoofing#3]
Thank you so much for this project. I really appreciate your work. 
You used OULU and CASIA dataset in your work. Can I get those datasets, it would be really helpful to me. 
Thank you in advance

**Comment by mortezagolzan** [comment]
> Thank you so much for this project. I really appreciate your work. You used OULU and CASIA dataset in your work. Can I get those datasets, it would be really helpful to me. Thank you in advance

Dear @AZuhaira,
unfortunately, I cannot share this data based on the policies. please contact [the owner](https://sites.google.com/site/oulunpudatabase/) of the mentioned dataset and ask them to share it with you.
